name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_2
      id: test_2
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_2_RESULTS: "${{steps.test_2.outputs.result}}"
      with:
        runners: test_2
